FROM openjdk:17.0.2-jdk
MAINTAINER Jason
VOLUME /home/ifans
RUN mrikr -p /home/ifans
WORKDIR /home/ifans
COPY ./jar/ifans-auth.jar /home/ifans/ifans-auth.jar
ENTRYPOINT ["java","-jar","ifans-auth.jar"]

